# Generated by Django 3.2.9 on 2021-11-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referer',
            new_name='referrer',
        ),
    ]
